// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysqlpetland

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImage = "images"

// Image mapped from table <images>
type Image struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginName string         `gorm:"column:origin_name;not null" json:"origin_name"`
	Name       string         `gorm:"column:name;not null" json:"name"`
	URL        string         `gorm:"column:url;not null" json:"url"`
	FloorID    int32          `gorm:"column:floor_id;not null" json:"floor_id"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
