// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysqlpetland

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePlace = "places"

// Place mapped from table <places>
type Place struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description" json:"description"`
	Address     string         `gorm:"column:address;not null" json:"address"`
	CategoryID  int32          `gorm:"column:category_id;not null" json:"category_id"`
	UserID      int32          `gorm:"column:user_id;not null" json:"user_id"`
	Active      bool           `gorm:"column:active;not null" json:"active"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Place's table name
func (*Place) TableName() string {
	return TableNamePlace
}
